apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sm-operator.fullname" . }}-manager-role
  labels:
    {{- include "sm-operator.fullLabels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
- apiGroups:
  - k8s.bitwarden.com
  resources:
  - bitwardensecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.bitwarden.com
  resources:
  - bitwardensecrets/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.bitwarden.com
  resources:
  - bitwardensecrets/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sm-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    {{- include "sm-operator.fullLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "sm-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "sm-operator.fullname" . }}-controller-manager'
  namespace: {{ .Release.Namespace }}
