apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sm-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    {{- include "sm-operator.fullLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.containers.serviceAccount.annotations | nindent 4 }}
