{{/*
Fail the render when the identity certificate password is a known-vulnerable
value.

Chart versions earlier than 2.0.0 generated the password with a template that
assigned the result of `lookup` (a map) to the password variable instead of a
random string. On a fresh install the looked-up secret does not exist, so Go
rendered the empty map as the literal string "map[]" and the identity.pfx was
encrypted with that publicly known value. See SHOT-159 / VULN-553.

Takes the password as an argument rather than reading it itself so the
comparison can be unit-tested without a cluster.

`certPresent` selects the remediation advice. When the certificate secret is
gone, the password secret is an orphan left behind by a previous release and the
rotation procedure cannot be followed - there is no pfx to re-encrypt - so the
operator is told to delete it instead.

Args (dict): password, secretName, namespace, certPresent
*/}}
{{- define "bitwarden.assertSafeIdentityCertPassword" -}}
{{- $vulnerable := list "map[]" -}}
{{- if has .password $vulnerable -}}
{{- $remedy := "" -}}
{{- if .certPresent -}}
{{-   $remedy = "Rotate the password before continuing. Rotation is done with kubectl and openssl and does not require Helm, so this block does not prevent you from fixing it:\nhttps://github.com/bitwarden/helm-charts/tree/main/charts/self-host#rotating-a-vulnerable-identity-certificate-password" -}}
{{- else -}}
{{-   $remedy = printf "The certificate secret this password belongs to no longer exists, so there is nothing to rotate - this secret is a leftover from a previous release. Delete it and retry:\n\n  kubectl delete secret %s -n %s" .secretName .namespace -}}
{{- end -}}
{{- fail (printf "\n\nThe identity certificate password in secret %q (namespace %q) is a known-vulnerable value generated by Bitwarden self-host chart versions earlier than 2.0.0 (SHOT-159 / VULN-553). The identity.pfx it protects is encrypted with a publicly known password.\n\nInstall and upgrade are both blocked while this value is in place.\n\n%s\n" .secretName .namespace $remedy) -}}
{{- end -}}
{{- end -}}
