---
apiVersion: batch/v1
kind: Job
metadata:
  name: "bitwarden-backup"
  labels:
    app.kubernetes.io/component: bitwarden-backup
    app: bitwarden-backup
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 1
  template:
    metadata:
      name: "bitwarden-backup"
      labels:
        app.kubernetes.io/component: bitwarden-backup
        app: bitwarden-backup
    spec:
      containers:
      - name: backup-db
        env:
        - name: MSSQL_CONN_STRING
          valueFrom:
            secretKeyRef:
              name: bitwarden-sql-connection-string
              key: globalSettings__sqlServer__connectionString
        image: "mcr.microsoft.com/mssql-tools"
        volumeMounts:
          - name: mssql-backups
            mountPath: /backups
        command:
          - "/bin/bash"
          - "-c"
        args: [
            "
            [ ! -f /backups/vault.bak ] || mv /backups/vault.bak \"/backups/vault.bak.$(date -r /backups/vault.bak -u +'%Y-%m-%dT%H:%M:%SZ')\";
            svr=\"$(echo \"${MSSQL_CONN_STRING}\" | grep -Po \"Data Source=tcp:\\K[^,]*(?=.*)\")\";
            pass=\"$(echo \"${MSSQL_CONN_STRING}\" | grep -Po \".*Password=\\K[^;]*(?=.*)\")\";
            echo \"$pass\" | /opt/mssql-tools/bin/sqlcmd -S $svr -U SA -q \"BACKUP DATABASE [vault] TO DISK = '/var/opt/mssql/backups/vault.bak' WITH FORMAT, INIT\"
            "
        ]
      restartPolicy: Never
      volumes:
        - name: mssql-backups
          persistentVolumeClaim:
            claimName: bitwarden-self-host-mssqlbackups
