apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "5a30c3dd-d7b9-4d32-8764-b06800c9e6ff"
  secretName: bw-sample-secret
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: e30f88bd-9e9c-42ae-83b7-b155012da672
      secretKeyName: test__secret__1
    - bwSecretId: 9f66ccaf-998e-4e5d-9294-b155012db579
      secretKeyName: test__secret__2
    - bwSecretId: c2d703cb-9ce0-43b4-a0ab-b155012dc651
      secretKeyName: test__secret__3
