apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "5a30c3dd-d7b9-4d32-8764-b06800c9e6ff"
  secretName: bw-sample-secret
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: af795aef-1605-4b51-92c0-b40c0130ff5f
      secretKeyName: test__secret__1
    - bwSecretId: d489d8d3-a7d6-4820-a3a8-b40c0131106d
      secretKeyName: test__secret__2
    - bwSecretId: 431a070e-35b1-4ed1-b8ac-b40c01311e8d
      secretKeyName: test__secret__3
