apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "5a30c3dd-d7b9-4d32-8764-b06800c9e6ff"
  secretName: bw-sample-secret
  authToken:
    secretName: bw-auth-token
    secretKey: token
