---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-cleanup"
  labels:
    app.kubernetes.io/component: post-delete-hook
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-cleanup"
      labels:
        app.kubernetes.io/component: post-delete-hook
    spec:
    {{- with .Values.general.nodeSelector }}
      nodeSelector:
    {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.general.tolerations }}
      tolerations:
    {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.serviceAccount.name }}
      serviceAccountName: "{{ .Values.serviceAccount.name }}"
    {{- end }}
      containers:
      - name: delete-resources
        command: [
          "/bin/sh", "-c"
        ]
        args: ['
          kubectl delete configmap {{ .Release.Name }}-config-map -n {{ .Release.Namespace }};
          kubectl delete configmap {{ .Release.Name }}-config-map-web -n {{ .Release.Namespace }};
          {{- if .Values.database.enabled }}
          kubectl delete secret "{{ .Release.Name }}-sql-connection-string" -n {{ .Release.Namespace }};
          {{- end }}
          kubectl delete secret {{ .Release.Name }}-identity-cert -n {{ .Release.Namespace }};
          kubectl delete secret {{ .Release.Name }}-identity-cert-password  -n {{ .Release.Namespace }};
          kubectl delete job {{ .Release.Name }}-setup;
          kubectl delete job {{ .Release.Name }}-migrator;
          echo "Done"
        ']
        image: "bitnami/kubectl:1.26.11"
      restartPolicy: Never
