{{- if .Values.database.enabled }}
{{- $dbServiceName := include "bitwarden.mssql" . }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-secret-sql"
  labels:
    app.kubernetes.io/component: pre-install-hook
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-secret-sql"
      labels:
        app.kubernetes.io/component: pre-install-hook
    spec:
    {{- with .Values.general.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.general.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.serviceAccount.name }}
      serviceAccountName: "{{ .Values.serviceAccount.name }}"
    {{- end }}
      containers:
      - name: create-resources
        command:
          - "/bin/sh"
          - "-c"
        args: ['
          kubectl create secret generic {{ .Release.Name }}-sql-connection-string -n {{ .Release.Namespace }}
            --from-literal=globalSettings__sqlServer__connectionString="Data Source=tcp:{{ $dbServiceName }},1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=$SA_PASSWORD;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True"

          echo "Done"
        ']
        image: "bitnami/kubectl:1.26.11"
        envFrom:
          - secretRef:
              name: "{{ .Values.secrets.secretName }}"
        volumeMounts:
        - name: temp
          mountPath: "/bitwarden"
        {{- if .Values.secrets.secretProviderClass}}
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        {{- end }}
      restartPolicy: Never
      volumes:
        - name: temp
          emptyDir:
            medium: Memory
        {{- if .Values.secrets.secretProviderClass}}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secrets.secretProviderClass }}
        {{- end }}
{{- end }}
