name: Build Self Host

on:
  push:
    branches:
      - BRE-131-split-workflows
  workflow_dispatch:

jobs:
  build-self-host:
    uses: ./.github/workflows/_build.yml
    with:
      chart_name: self-host