name: Release Self-Host 
run-name: Release Self-Host - ${{ inputs.release_mode }}

on:
  workflow_dispatch:
    inputs:
      release_mode:
        description: "Release Mode"
        default: "Standard Release"
        type: choice
        options:
          - Standard Release
          - Dry Run

jobs:
  build-self-host:
    uses: ./.github/workflows/_release.yml
    with:
      build_workflow: build-self-host.yml
      dry_run: ${{ inputs.release_mode == 'Dry Run' }}