name: Update Versions - Self Host

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run — skips committing to main"
        required: false
        default: false
        type: boolean

permissions: {}

jobs:
  trigger:
    name: Trigger update versions
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Trigger update versions
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          task: helm-charts-update-versions
